### ISSUE TITLE
Launch to production

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#215]
- [x] implement new feedback email + jira queue
- [x] address geomonitor prod issues
  - [x] refactor the way tiles are checked
  - [x] cleanup database of old statuses https://github.com/geoblacklight/geomonitor/issues/41
- [x] move geomonitor to new puppet - SAR-2661
  - [x] dev
  - [x] stage
  - [x] prod
- [x] recreate *-dev - SAR-2662
- [ ] regenerate index with new download as facet #212 
- [x] document index generation process (see [Consul](https://consul.stanford.edu/display/SULAIRGIS/HOWTO+-+Build+EarthWorks+Solr+Index))
- [x] soft launch to gis list
- [x] load testing - SAR-2664
  - [x] initial test
  - [x] test after system changes
- [ ] security review - SAR-2663
- [ ] precache big downloads?
- [x] have nodes share cache #231 
- [x] db replication (https://github.com/sul-dlss/gis-robot-suite/issues/7)
- [ ] geoserver replication (https://jirasul.stanford.edu/jira/browse/SAR-2684)
- [x] install new relic on monitor & earthworks #216 
  - [x] earthworks
  - [x] monitor - done on stage, waiting on prod new puppet
- [x] turn on Google indexing
- [x] new puppetize dbs - https://jirasul.stanford.edu/jira/browse/SAR-2685
- [ ] new puppetize pods - https://jirasul.stanford.edu/jira/browse/SAR-2685
- [x] notifications to SMS - https://jirasul.stanford.edu/jira/browse/SAR-2670
- [x] autocomplete and spelling #241 
- [x] remove beta from branding #246 
- [ ] schedule a celebration dinner!

**Comment by mejackreed** [comment]
cc @eefahy

**Comment by drh-stanford** [comment]
i don't think we ever did a dinner :). closing
