### ISSUE TITLE
coordinate effort to deploy to production

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#391]
We need a coordinated effort to push to production:

- [x] Complete #387 
- [x] Complete index for `kurma-earthworks-v1-prod` (see #337)
- [x] Swap EarthWorks to that index in production (in shared_configs repo, see #360 )
- [x] Deploy EarthWorks to production
- [x] Fire off GeoMonitor and debug issues with unavailiability as needed
- [x] Add "cron job" or something for running GeoMonitor periodically, see https://github.com/sul-dlss/earthworks/issues/401
- [x] Push `gis-robot-suite` to production and debug issues with a single object with @kimdurante
- [x] Create PR in OpenGeoMetadata for that new object, see https://github.com/OpenGeoMetadata/edu.stanford.purl/pull/28
- [x] Decommission servers, see #341 and https://github.com/sul-dlss/operations-tasks/issues/1586  and https://github.com/sul-dlss/operations-tasks/issues/1587
- [x] Accession an Index Maps layer, see https://github.com/sul-dlss/earthworks/issues/388
- [x] Upgrade to GeoBlacklight 1.8 which has the new index maps functionality
- [ ] Correct/address/punt on findings from #387, #394
- [ ] Declare victory!

**Comment by mejackreed** [comment]
> Declare victory!

👏
