### ISSUE TITLE
Design support for relationships between datasets in EarthWorks

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#592]
Early GeoBlacklight designs around this here: https://drive.google.com/file/d/0BzWuWHFTTIPEaC1KYkVyRkVfTUU/view?usp=sharing

Aim to address some questions:

 - How can we elevate and collapse collection level records in EarthWorks/ GeoBlacklight?
 - Evaluate existing "data relations widget" in GeoBlacklight (see: https://geo.nyu.edu/catalog/nyu-2451-34679)
 - Look at relationships in GeoBlacklight survey. What types could we accomodate from existing SDR models? https://docs.google.com/spreadsheets/d/1ypDwV6LalWq7CdHwU470BKcvYPGbwLRn_q4Eg66p8cc/edit#gid=343469996

Upstream work:
- [x] https://github.com/geoblacklight/geoblacklight/issues/906
- [x] https://github.com/geoblacklight/geoblacklight/issues/907
- [x] https://github.com/geoblacklight/geoblacklight/issues/908
- [x] https://github.com/geoblacklight/geoblacklight/issues/909
- [x] https://github.com/sul-dlss/searchworks_traject_indexer/issues/459

**Comment by ggeisler** [comment]
Related tickets in GeoBlacklight:

- https://github.com/geoblacklight/geoblacklight/issues/906
- https://github.com/geoblacklight/geoblacklight/issues/907
- https://github.com/geoblacklight/geoblacklight/issues/908
- https://github.com/geoblacklight/geoblacklight/issues/909

However, those tickets focus on how we could _display_ item relationships. More analysis needs to be done to figure out how those three distinct types of relationships can be (programmatically, presumably) determined.
