### ISSUE TITLE
Convert gisDiscovery workflows to searchworks_traject_indexer

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#628]
This work will aim to remove the multiple places where content is indexed into EarthWorks.

Things we need to account for:

`generate-geoblacklight`
1. mods -> GeoBlacklight schema metadata conversion https://github.com/sul-dlss/gis-robot-suite/blob/master/robots/gisDiscovery/generate-geoblacklight.rb#L37
1. "enhance" geoblacklight schema https://github.com/OpenGeoMetadata/GeoCombine/blob/934e86f0ed7f29ab48e28a237ae2b8e9e2d7727c/lib/geo_combine/geoblacklight.rb#L38-L48 https://github.com/sul-dlss/gis-robot-suite/blob/master/robots/gisDiscovery/generate-geoblacklight.rb#L40

- [x] name="dc_creator_sm"
- [?] name="dc_description_s" (XSLT is more selective?)
- [x] name="dc_format_s"
- [x] name="dc_identifier_s"
- [x] name="dc_language_s"
- [x] name="dc_publisher_s"
- [?] name="dc_rights_s"  (provided to the XSLT)
- [?] name="dc_subject_sm" (some business about ISO19115topicCategory URIs?)
- [x] name="dc_title_s"
- [x] name="dc_type_s"
- [x] name="dct_isPartOf_sm"
- [x] name="dct_issued_s"
- [?] name="dct_provenance_s"  (`mods:recordInfo/mods:recordContentSource/text()` (likely CSt) vs hard-coded 'Stanford')
- [x] name="dct_references_s"
  - [x] schema.org/url
  - [x] schema.org/downloadUrl
  - [x] mods/v3
  - [x] isotc211
  - [x] wfs (format=Shapefile)
  - [x] wcs (format= GeoTIFF or ArcGRID)
  - [x] wms
- [x] name="dct_spatial_sm"
- [x] name="dct_temporal_sm"
- [x] name="geoblacklight_version"
- [x] name="layer_geom_type_s"
- [x] name="layer_id_s"
- [x] name="layer_modified_dt"
- [x] name="layer_slug_s"
- [x] name="solr_geom"
- [x] name="solr_year_i"
- [x] name="stanford_rights_metadata_s"

Non-XSLT:
- [x] https://github.com/OpenGeoMetadata/GeoCombine/blob/934e86f0ed7f29ab48e28a237ae2b8e9e2d7727c/lib/geo_combine/geoblacklight.rb#L38-L47
- [x] something something index maps

`load-geoblacklight`
1. We should get this for free from our pipeline searchworks_traject_indexer

`export-opengeometadata`
1. Figure out how we can continue to export content here: https://github.com/opengeometadata/edu.stanford.purl automagically would be nice

Also, can we notify @kimdurante when items fail to index? Use honeybadger?

**Comment by mejackreed** [comment]
Spinning out some of this work here: 
 - [ ] Convert pending specs to 🍏 https://github.com/sul-dlss/searchworks_traject_indexer/issues/454

**Comment by cbeer** [comment]
i think there’s either a typo in the mods->geoblacklight XSLT (or in our data)

https://github.com/sul-dlss/gis-robot-suite/blob/master/lib/xslt/mods2geoblacklight.xsl#L150-L154 has `ISO19115topicCategory`, but spot-checking our data has `ISO19115TopicCategory` (capital T in topic).

I'm not sure how to verify current practice across all our geo data, and I don't know if the translation step is even needed/wanted if we haven't noticed until now?

**Comment by mejackreed** [comment]
I think that is ok and should be fine. Since it falls through to the value we want to actually provide for the facet, we should be fine here. 

Looking at https://purl.stanford.edu/gk341mw7101.mods

`Imagery and Base Maps` seems better than `imageryBaseMapsEarthCover`. Maybe an uncovered bug that we never needed to fix?

And the GeoCombine method `enhance_metadata` aims to convert this back anyways: https://github.com/OpenGeoMetadata/GeoCombine/blob/934e86f0ed7f29ab48e28a237ae2b8e9e2d7727c/lib/geo_combine/subjects.rb#L6-L27

**Comment by mejackreed** [comment]
Remaining tasks as I understand them here:
 - [ ] Ship the GitHub actions thing into production
 - [ ] Finalize approach for restricted data

**Comment by mejackreed** [comment]
This has been resolved now both in searchworks_traject_indexer and in OpenGeoMetadata/edu.stanford.purl
